pipeline {
    agent {
        label 'docker-integration-test'
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Elastic') {
            steps {
                sh 'runuser -l elasticsearch -c /usr/share/elasticsearch/bin/elasticsearch'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'chmod +x ./jenkins/scripts/deliver.sh'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}